version: "3"
services:
  db:
    container_name: mongo
    image: mongo
    volumes:
      - ./mongodata:/data/db
    environment:
      MONGO_INITDB_DATABASE: e-eommerce
    ports:
      - "27017:27017"
    networks:
      - network

networks:
  network:
    driver: bridge
